#!/usr/bin/env python3
"""Index every presentation and poster in the repo by the patterns they use.

Run with no arguments for a summary table of all decks. Use --pattern to find decks
that demonstrate a pattern (a CSS class, pandoc div syntax, "gsap", anything). Use
--deck for the per-slide detail view of one deck.

Run it through uv, so that it can import the parser:

    uv run python deck-index.py
    uv run python deck-index.py --pattern "card--maroon"
    uv run python deck-index.py --pattern "gsap|auto-animate"
    uv run python deck-index.py --deck fulbright-ai-capabilities
    uv run python deck-index.py --json

Slide ids and counts come from `presentation_maker.deck`, the same parser `pres check`
uses, which is verified against the rendered HTML of every deck. Do not reintroduce a
local heading regex or slug rule here: the ids are meant to be pasted straight into
`pres shot --slide <id>`, and the previous hand-rolled versions got 20 of 158 wrong.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Repo root is four levels up from this script: scripts/ -> reference-decks/ ->
# skills/ -> .agents/ -> repo root.
REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO_ROOT / "src"))

try:
    from presentation_maker.deck.parser import parse_deck  # noqa: E402
except ImportError as error:  # pragma: no cover - a setup problem, not a code path
    sys.exit(
        f"Could not import the deck parser ({error}).\n"
        "Run this through uv:  uv run python " + str(Path(__file__).name)
    )

# Class names defined in the shared stylesheets. A deck-local class not in this set
# (and not a reveal.js built-in) had to be defined by the deck itself.
SHARED_SCSS = [
    REPO_ROOT / "styles" / "components.scss",
    REPO_ROOT / "styles" / "poster.scss",
    REPO_ROOT / "styles" / "poster_elements.scss",
]

# reveal.js / Quarto internals that show up as .foo selectors but are not ours.
BUILTIN_CLASSES = {
    "reveal", "slides", "slide-background", "slide-background-content",
    "slide-logo", "slide-number", "backgrounds", "progress", "controls",
    "quarto-title-block", "title-slide", "panel-tab", "quarto-figure",
}

# The class census is still a regex over .scss. It over-reports classes generated by
# @for loops and &-- nesting, which is why it only ever labels things "deck-local"
# rather than "undefined". Resolving SCSS properly is its own piece of work.
CLASS_RE = re.compile(r"\.([a-zA-Z][a-zA-Z0-9_-]*)")
DUPLICATE_SUFFIX_RE = re.compile(r"-\d+$")


def source_files(entry_dir: Path) -> list[Path]:
    """All human-written source files for a deck: qmd/scss/yml/html, no builds."""
    files = []
    for p in sorted(entry_dir.rglob("*")):
        if not p.is_file():
            continue
        if p.suffix not in {".qmd", ".scss", ".yml", ".yaml", ".html"}:
            continue
        if "index_files" in p.parts or p.name == "index.html":
            continue
        files.append(p)
    return files


def scss_classes(path: Path) -> set[str]:
    try:
        return set(CLASS_RE.findall(path.read_text(encoding="utf-8", errors="replace")))
    except OSError:
        return set()


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def index_entry(entry_dir: Path, kind: str, shared: set[str]) -> dict:
    model = parse_deck(entry_dir / "index.qmd")
    all_text = "\n".join(read(f) for f in source_files(entry_dir))

    local_scss = entry_dir / "styles.scss"
    local_classes = scss_classes(local_scss) if local_scss.exists() else set()
    custom = sorted(
        (local_classes - shared) - BUILTIN_CLASSES
        - {"card", "citation", "term", "reveal", "footer", "figure", "left", "right"}
    )

    # Partials are the files actually pulled in by {{< include >}}, in include order.
    # Globbing partials/*.qmd instead used to list files no deck included and to sort
    # their slides to the end rather than to their real positions.
    partials = [
        str(inc.resolved.relative_to(entry_dir))
        if inc.resolved and entry_dir in inc.resolved.parents
        else inc.raw
        for inc in model.includes
    ]

    return {
        "slug": entry_dir.name,
        "kind": kind,
        "title": str(model.frontmatter.get("title", "?")),
        "slides": len(model.slides),
        "fragments": len(re.findall(r"\.fragment\b", all_text)),
        "columns": len(re.findall(r"\{\.columns", all_text)),
        "gsap": "gsap" in all_text.lower(),
        "auto_animate": "auto-animate" in all_text,
        "partials": partials,
        "local_scss_bytes": local_scss.stat().st_size if local_scss.exists() else 0,
        "custom_classes": custom,
        "slide_list": [
            {
                "index": s.index,
                "id": s.slide_id,
                "heading": s.heading,
                "file": str(s.origin.file.relative_to(REPO_ROOT)),
                "line": s.origin.line,
                "duplicate": s.slide_id != s.base_id,
            }
            for s in model.slides
        ],
    }


def print_table(entries: list[dict]) -> None:
    def anim(e):
        tags = []
        if e["gsap"]:
            tags.append("gsap")
        if e["auto_animate"]:
            tags.append("aa")
        return "+".join(tags) or "-"

    print(f"| {'slug':<30} | {'k':<2} | {'title':<34} | sld | frag | col | anim | partials | scss | custom classes |")
    print(f"|{'-' * 32}|----|{'-' * 36}|-----|------|-----|------|----------|------|----------------|")
    for e in entries:
        title = e["title"][:34]
        print(
            f"| {e['slug']:<30} | {e['kind'][0]:<2} | {title:<34} "
            f"| {e['slides']:>3} | {e['fragments']:>4} | {e['columns']:>3} "
            f"| {anim(e):<6} | {len(e['partials']):>8} "
            f"| {e['local_scss_bytes'] // 1024:>4}K | {len(e['custom_classes']):>14} |"
        )
    print("\n(k = d=eck / p=oster, sld = `##` headings, scss = deck-local styles.scss)")
    print("Use --deck <slug> for slide headings and custom class names.")


def print_detail(e: dict, entry_dir: Path) -> None:
    print(f"# {e['slug']} ({e['kind']}) — {e['title']}")
    print(f"dir: {entry_dir}")
    print(f"slides: {e['slides']}  fragments: {e['fragments']}  columns: {e['columns']}")
    if e["gsap"]:
        print("uses: GSAP")
    if e["auto_animate"]:
        print("uses: auto-animate")
    if e["partials"]:
        print(f"includes ({len(e['partials'])}): {', '.join(e['partials'])}")
    if e["custom_classes"]:
        print(f"deck-local classes: {', '.join(e['custom_classes'])}")
    if e["local_scss_bytes"]:
        print(f"local styles.scss: {e['local_scss_bytes'] // 1024}K")

    print("\n## Slides (id for `pres shot --slide <id>`, in deck order)")
    source_name = "index.qmd"
    for slide in e["slide_list"]:
        origin = Path(slide["file"]).name
        where = "" if origin == source_name else f"  [{origin}]"
        dup = "  <- duplicate heading; run `pres check`" if slide["duplicate"] else ""
        print(f"  {slide['index']:>3}  {slide['id']:<50} {slide['heading']}{where}{dup}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pattern", help="only entries whose sources match this regex")
    ap.add_argument("--deck", help="per-slide detail for one slug")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument("--root", type=Path, default=REPO_ROOT,
                    help="repo root (default: inferred from script location)")
    args = ap.parse_args()

    root = args.root.resolve()
    shared = set()
    for p in SHARED_SCSS:
        shared |= scss_classes(p)

    entries = []
    for base, kind in ((root / "presentations", "deck"), (root / "posters", "poster")):
        if base.is_dir():
            entries += [index_entry(d, kind, shared)
                        for d in sorted(base.iterdir())
                        if (d / "index.qmd").is_file()]
    entries.sort(key=lambda e: (e["kind"], e["slug"]))

    if args.deck:
        match = [e for e in entries if e["slug"] == args.deck]
        if not match:
            print(f"no entry named {args.deck!r}; known: {', '.join(e['slug'] for e in entries)}",
                  file=sys.stderr)
            return 1
        if args.json:
            print(json.dumps(match[0], indent=2))
        else:
            print_detail(match[0], root / ("presentations" if match[0]["kind"] == "deck" else "posters") / args.deck)
        return 0

    if args.pattern:
        rx = re.compile(args.pattern)
        kept = []
        for e in entries:
            d = root / ("presentations" if e["kind"] == "deck" else "posters") / e["slug"]
            hits = {}
            for f in source_files(d):
                n = len(rx.findall(read(f)))
                if n:
                    hits[str(f.relative_to(root))] = n
            if hits:
                e = dict(e)
                e["matches"] = hits
                kept.append(e)
        entries = kept

    if args.json:
        print(json.dumps(entries, indent=2))
    elif not entries:
        print("no matching entries")
    else:
        print_table(entries)
        if args.pattern:
            print(f"\nmatches for /{args.pattern}/:")
            for e in entries:
                for f, n in e["matches"].items():
                    print(f"  {e['slug']}: {f} ({n}x)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
